services:
  bitcoin-core:
    container_name: testnet-bitcoin-core
    command: -printtoconsole -txindex -server -rpcuser=user -rpcpassword=password -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0 -testnet
    ports:
      - "18332:18332"

  ion-bitcoin:
    container_name: testnet-ion-bitcoin
    environment:
      - ION_BITCOIN_CONFIG_FILE_PATH=/config/docker-testnet-bitcoin-config.config
      - ION_BITCOIN_VERSIONING_CONFIG_FILE_PATH=/config/testnet-bitcoin-versioning.config

  ion-core:
    container_name: testnet-ion-core
    environment:
      - ION_CORE_CONFIG_FILE_PATH=/config/docker-testnet-core-config.config
      - ION_CORE_VERSIONING_CONFIG_FILE_PATH=/config/testnet-core-versioning.config
